### PR TITLE
Fix compatibility with flutter 3 [Breaking]

### PR DESCRIPTION
**Pull request by hasanmhallak**
**Breaking Changes**
- change `onRequestPermissionsResult` permissions  to a non-nullable `Array<out String>`.
- remove nullability form `WidgetsBinding` instance.

This has been tested on both Android & iOS.

### CODE REVIEW

**Comment by captain-woof** [comment]
@hasanmhallak Hey! Can we have this merged for a release?

**Comment by hasanmhallak** [comment]
@captain-woof sure thing man, it's an open source contribution.

**Comment by hasanmhallak** [comment]
@captain-woof I didn't get what mean. I'm not sure if I can merge this for a release, the original developer must accept this pull request first.

**Comment by DhavalRKansara** [comment]
@hasanmhallak Thanks for your Contribution. We have reviewed your PR, where some of the changes have been already merged within the main branch, while a few changes from your PR are not required for flutter 3.0 migration.

**Pull request closed without merging**
